language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/parallel-lint --exclude vendor . bin/shootproof-cli
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs src bin bin/shootproof-cli --standard=psr2 -sp

after_script: php vendor/bin/coveralls
